### ISSUE TITLE
EMC condenser cause fps lag

### ISSUE THREAD

**Issue by Zaflis** [Mordenkainen/EquivalentEnergistics#47] opened 2015-12-11 04:40 UTC
Just started using this mod on a endgame base. Connected just 1 EMC condenser to ME network and framerate dropped from 65 to 40. Broke it, lag away, place again lag comes back.

Using version 0.6 of the mod, appliedenergistics2-rv3-alpha-9.

**Comment by Mordenkainen** [comment] 2015-12-11 18:47
Duplicate of #39

Please do not open duplicate issues. Instead add info to the existing issue, thanks.

**Closed by Mordenkainen** 2015-12-11 18:47 UTC
