### ISSUE TITLE
Items missing from EE that are in the ProjectE tablet

### ISSUE THREAD

**Issue by sedarious** [Mordenkainen/EquivalentEnergistics#66] opened 2016-10-03 02:16 UTC
Using EquivalentEnergistics - 0.6 - 1.7.10

Several items from the ProjectE tablet are not present using EE in the AE2 interface.  In particular none of the gears from Thermal Expansion (4315:12,129,128,136,135,138,140), several ingot types (TE - 4315:71,76,66,72,74,67,73,9 ; Mekanism-  5753:1, EnderIO 5843:1,2,6), sulfur (4315:16), Signalum Nugget (4315:106).

Learning/unlearning of other items seems to be working fine and updating appropriately.

I'm using the Mianite Reborn pack if that is relevant.  Let me know if there are any files that would be helpful for me to post.

**Comment by Mordenkainen** [comment] 2016-10-03 11:29
Closing as a duplicate of #41. See that issue for a workaround.

**Closed** 2016-10-03 12:28 UTC

**Comment by sedarious** [comment] 2016-10-03 18:58
Thank you!  The workaround resolves the issue after a server restart.

**Comment by MaPePeR** [comment] 2016-10-03 19:29
This should not happen anymore, the fix for that should have been merged and released in ProjectE.

Try updating ProjectE please.

**Comment by Mordenkainen** [comment] 2016-10-03 19:38
I agree, but it seems some packs are still using old Project-E builds. BTW, neat that you are still paying attention to the project! I hope to have a release in the near future that has some interesting additional integration with PE like the ability to charge EMC storage cells in relays and using Klein Stars to import EMC into the system at a reduced cost. Then next up will be EMC import/export busses that will extract/insert EMC for condensers, relays, etc.

**Comment by sedarious** [comment] 2016-10-03 19:40
I'd give a newer version a go, but we're already using "EquivalentEnergistics - 0.6 - 1.7.10.jar" which seems to be the most recent that I can find.  Can you point me in the direction of a newer release that is 1.7.10 compatible?

**Comment by Mordenkainen** [comment] 2016-10-03 19:42
Newer Project-E, not Equivalent Energistics. The issue was on their side and should be resolved in newer builds.

**Comment by sedarious** [comment] 2016-10-03 19:48
My misread - sorry!  The pack is using "ProjectE-1.7.10-PE1.10.0.jar" which looks like the most recent release for 1.7.10 per https://minecraft.curseforge.com/projects/projecte/files.

**Comment by MaPePeR** [comment] 2016-10-03 20:10
Then the fix didn't work :cry:

**Comment by Mordenkainen** [comment] 2016-10-03 20:15
Hmmm. works in my dev code, so perhaps there was an issue on both sides?
