### ISSUE TITLE
EE server crash when inserting a Alchemical Tome into an Ultimate EMC Assembler.

### ISSUE THREAD

**Issue by Seyeght** [Mordenkainen/EquivalentEnergistics#101] opened 2018-07-12 08:49 UTC
This is the clip of it happening live:
https://clips.twitch.tv/TubularMuddyTrufflePJSalt

Here is the crash log of the first crash (the one in the clip)
https://pastebin.com/v7c8aDiZ

on reboot as it loads the world it creates an identical crash log

**Comment by Seyeght** [comment] 2018-07-12 09:24
at first I thought the tome inserted into the Assembler might have been one that didnt have an owner assigned, but we have tested again, and it caused the same crash even when making sure it had an owner on the Tome.

**Comment by Seyeght** [comment] 2018-07-12 10:17
Not sure if this helps pin down where in the code the error is, but the Ultimate EMC Assembler is not connected to the AE system at the time we are trying to put the tome into it.

**Comment by Seyeght** [comment] 2018-07-12 10:18
Will test later if the error repeats when it is connected to the network.

**Comment by Mordenkainen** [comment] 2018-07-13 13:55
Ok, so first comment would be that you only need one tome. A tome inserted into ANY ENC Assembler allows all Assemblers on the network to craft all items in the tome.

So, you only need one tome per player per network.

Secondly, this has nothing to do with the tome. PE changed thier API in such a way to break all PE addons. I need to update for the new API, but for the time being, downgrade your PE.

Closing this as it is a dupe of #98.

**Closed as completed by Mordenkainen** 2018-07-13 13:55 UTC
