### ISSUE TITLE
Crash when logging after scheduling a craft on Ae2

### ISSUE THREAD

**Issue by deded1423** [Mordenkainen/EquivalentEnergistics#21] opened 2015-07-12 00:16 UTC
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 12/07/15 2:03
Description: Ticking block entity

java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at appeng.tile.events.AETileEventHandler.tick(AETileEventHandler.java:62)
	at appeng.tile.AEBaseTile.func_145845_h(AEBaseTile.java:180)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at appeng.tile.events.AETileEventHandler.tick(AETileEventHandler.java:50)
	... 12 more
Caused by: java.lang.NullPointerException
	at com.mordenkainen.equivalentenergistics.tiles.TileEMCCrafter.onTick(TileEMCCrafter.java:194)
	... 17 more

**Comment by Mordenkainen** [comment] 2015-07-12 22:12
Duplicate of issue #20

**Closed by Mordenkainen** 2015-07-12 22:12 UTC
Labels: duplicate
