### ISSUE TITLE
Crash with ProjectE 1.8.0

### ISSUE THREAD

**Issue by AlexPlus117** [Mordenkainen/EquivalentEnergistics#32] opened 2015-08-07 16:18 UTC
The game crashes on startup with newest version of ProjectE. Here is the crash-report: http://pastebin.com/J3AgrswT

**Comment by Mordenkainen** [comment] 2015-08-07 16:45
The new ProjectE version changes the API. I am aware of the issue and should have an update this weekend.

Closing as this is sort of a duplicate of #25

**Closed by Mordenkainen** 2015-08-07 16:45 UTC
Labels: duplicate
