### ISSUE TITLE
EMC Condenser framerate drop

### ISSUE THREAD

**Issue by watlok** [Mordenkainen/EquivalentEnergistics#39] opened 2015-08-27 21:53 UTC
When an EMC Condenser is connected to an ME network it drops my fps from 140 to 30, and in a base with multiple condensers fps is in the single digits. Breaking the condensers restores framerate back to normal.

 If the condenser is not connected to a network, like placing it on the ground, it does not drop framerate. 

This happens in creative test worlds as well as an actual survival server.

EE version: 0.3
AE2 version: rv2-stable-10
FML: 7.10.99.99
Forge: 10.13.4.1448
ProjectE version: 1.7.10-PE1.7.3

It happens with and without fastcraft.

**Comment by Mordenkainen** [comment] 2015-08-31 16:33
I suspect this is a symptom of AE calling some "expensive" methods more often than I had anticipated. I am working on this, and can not recreate the issue with my current development version.

I will leave this issue open and set the "retest with latest" tag when the new version is ready. If you could recheck it at that time and let me know if it addresses your issues, it would be appreciated.

**Comment by MaPePeR** [comment] 2015-08-31 18:04
So this is just a duplicate of #36 ?

**Comment by watlok** [comment] 2015-08-31 18:37
Shouldn't be a duplicate of #36, because the framerate lag is clientside while on a server. The server's tps is fine as far as I can tell.

**Comment by Mordenkainen** [comment] 2015-08-31 18:46
The code that handles communication to the AE network has quite a bit of unneeded overhead. This is because I cheated and used AE internal classes rather than write my own. This should be resolved in the next version, and if the problem still exists we will need to look a little deeper.

**Comment by Mordenkainen** [comment] 2015-09-06 03:41
Please retest with 0.6 and see if this is still an issue.

**Comment by jozefjan** [comment] 2015-09-25 15:51
My frames still drop with EquivalentEnergistics - 0.6 - 1.7.10.
Frames are ok when the condenser has 0 emc stored though.

Mods:
appliedenergistics2-rv2-stable-10
ProjectE-1.7.10-PE1.9.2

Can provide more details if needed.

**Comment by Mordenkainen** [comment] 2015-09-25 16:43
Ok, the information that it only happens when the Condenser contains EMC is helpful.

I'll look into it and see if I can find the cause.

**Comment by mccoole** [comment] 2016-03-02 03:34
I'm seeing this as well with ae2-stable-10 and version 0.6.  In my case it doesn't matter if the condenser has EMC or not.  Just connecting it immediately causes the FPS drop and it stops when its removed.

**Closed** 2017-03-08 16:35 UTC
Labels: investigating
