### ISSUE TITLE
[1.12.2]Servercrash Autocrafting

### ISSUE THREAD

**Issue by ghost** [Mordenkainen/EquivalentEnergistics#128] opened 2018-09-13 18:03 UTC
https://paste.myftb.de/ajugesonez

EquivalentEnergistics: 0.8.2
ProjectE: PE1.3.1B
appliedenergistics2: rv5-stable-11

**Comment by MaPePeR** [comment] 2018-09-13 18:36
EquivalentEnergistics is not yet compatible with ProjectE 1.3.1B. Downgrade ProjectE.

**Comment by Mordenkainen** [comment] 2018-10-13 03:15
Dupe of #98

**Closed as completed by Mordenkainen** 2018-10-13 03:15 UTC
Labels: duplicate
