### ISSUE TITLE
Can't start any World with new EE3 509

### ISSUE THREAD

**Issue by king05** [Mordenkainen/EquivalentEnergistics#50] opened 2016-01-09 10:36 UTC
Hi, first of all a happy new year.
After I updated to the newest EE3 Version I can't start neither an existing world nor an new world.

https://dl.dropboxusercontent.com/u/30828902/No%20world%20start.avi

here you can see that i'm trying both, start an existing and a new world.. nothing is working. 
When i downgrade to EE3 version 507 it works fine.

https://paste.ee/r/GlUm5
https://github.com/pahimar/Equivalent-Exchange-3/issues/1029

When i disabled equivalent energistics i can start the worlds again. 
(I got another crash that doesn't belong to your mod... https://github.com/pahimar/Equivalent-Exchange-3/issues/1028 )

Hope you can help me.
Greetings from Germany,
king05

Edit:
I don't know if the problem is betwen your mod and ProjectE (found this in the paste.ee document)
http://pastebin.com/uGcstXwx

**Comment by Mordenkainen** [comment] 2016-01-09 14:20
I'm not sure what the cause of the issue is. It looks like something deleted the EMC value of the EMC Crystals.

Are you altering EMC values using console commands or an EMC tweaking mod?

**Comment by king05** [comment] 2016-01-09 22:11
No i don't do anything like this... the only mod i use is ae2ee3addon which adds emc values for ae2... but this mod is disabled atm because i use ae2 rv3...

**Comment by Mordenkainen** [comment] 2016-01-10 20:58
FYI, this mod is for AE2 RV2. It does not play nice with RV3.

**Comment by king05** [comment] 2016-01-11 19:27
sorry, but which mod do you mean with FYI?... I'm to stupid to find it ... :D

**Comment by king05** [comment] 2016-01-11 19:45
ok..... this mod didn't cause any crash since i have updatet to ae2 rv3...
 i just tested to start a world without your mod and the world did start but than it did cash like it was discribed in #1028 in Equivalent excange post.

If you want i can test a little bit with EE3 verison 507 and ae2 rv3 and your mod to give you feedback how everything works for me....

Greetings king05

**Comment by Mordenkainen** [comment] 2016-05-05 00:21
Closing as it seems EE3 508/508 was not officially released, and seems to have reports of causing random crashes left and right.

**Closed by Mordenkainen** 2016-05-05 00:21 UTC
