### ISSUE TITLE
[Issue] Crash with ASM

### ISSUE THREAD

**Issue by accessdenied0** [Mordenkainen/EquivalentEnergistics#44] opened 2015-10-18 15:46 UTC
Dear @Mordenkainen,

I tried to add you mod to my world recently but with this mod I'm not longer able to load up my worlds. I was able to figure out that your mod conflicts with the AdvancedSystemsManager mod.

I already posted the issue over there: https://github.com/hilburn/AdvancedSystemsManager/issues/84

access_denied

**Comment by Mordenkainen** [comment] 2015-10-18 17:25
It appears the following code within FML is blowing up:
```java
        public UniqueIdentifier(String string)
        {
            String[] parts = string.split(":");
            this.modId = parts[0];
            this.name = parts[1];
        }
```

It almost seems like one of my items is not being tagged with the ModID correctly. But, I don't know which item it is. I will try implementing similar code directly within EqE and see if I can determine the cause.

Code to duplicate:
https://github.com/hilburn/AdvancedSystemsManager/blob/master/src/main/java/advancedsystemsmanager/helpers/ModItemHelper.java#L30

**Comment by Mordenkainen** [comment] 2016-05-04 14:47
Fixed on ASM's side.

**Closed by Mordenkainen** 2016-05-04 14:47 UTC
