### ISSUE TITLE
Some items learned in transmutation tablet won't show in AE system.

### ISSUE THREAD

**Issue by alven4** [Mordenkainen/EquivalentEnergistics#54] opened 2016-03-09 16:50 UTC
I taught my transmutation tablet tin ingot, copper ingot, lead ingot, tin gear and copper gear (all from TE) but none of those items shown up in terminal as craftable. After I taught transmutation tablet tin ingot from Galacticraft, it showed up in terminal. 

I am using version 0.6 of Equivalent Energistics and playing modpack Project Ozone.

**Comment by Belgabor** [comment] 2016-03-11 18:03
I can confirm that. Ingots, nuggets and gears of TF materials don't work, blocks do. Other items (in Project Ozone) that don't work are AE cables and busses, on the other hand processors and interfaces work.

**Comment by Belgabor** [comment] 2016-03-11 18:09
Additional note: These items also do not get converted into crystals if you pipe them into the EMC condenser, they just end up in the system.

**Comment by Mordenkainen** [comment] 2016-05-04 14:43
Duplicate of #41

Updated status can be found in that issue.

**Closed by Mordenkainen** 2016-05-04 14:43 UTC
